User Objects and Layout API
NinaBianca/Sanquin-API pull request #2
Opened 2024-11-18 11:11 UTC by NinaBianca

This pull request introduces several changes to the API, including switching to an asynchronous MongoDB client, adding a new router for user-related endpoints, and defining new Pydantic models for user data. The most important changes are summarized below:

### Database Connection:

* [`api/dependencies.py`](diffhunk://#diff-e82360825567810a0ff980e514645a2494c80fc525f0c77d59a61bb2b30437c3R1-R14): Switched from synchronous `MongoClient` to asynchronous `AsyncIOMotorClient` for database operations.

### Application Setup:

* [`api/main.py`](diffhunk://#diff-c2c3b0c64a2690193a471cfc8068fcb622a23e1b4323c693b6ba20835f26fb88L1-R16): Added `dotenv` to load environment variables and included the new `users` router. Updated the root endpoint message.

### User Models:

* [`api/models/user/update_user.py`](diffhunk://#diff-236367ff69a9ddd718bfb5f3b45648e67df34c9f9b44f1fe2a5dcc50a29f2aa5R1-R8): Added `UpdateUserModel` for updating user information with optional fields.
* [`api/models/user/user.py`](diffhunk://#diff-1e2921c0a6b5c3f88ed9530af7f2cf1eef9a48132172d2cf81e8e7bb83f84b0bR1-R14): Defined `UserModel` with fields for `id`, `name`, `email`, `password`, and `role`.
* [`api/models/user/user_collection.py`](diffhunk://#diff-4c0643e0eb232cb900df3c38328878801e694540d24193f9192b3248f3b0de31R1-R7): Created `UserCollection` model to handle a list of `UserModel` instances.

### User Router:

* [`api/routers/users.py`](diffhunk://#diff-20917c5a4aa1b2561e20cb2977adc9d59efb9a62774c51f632dac15e9c43a1c6R1-R34): Added new routes for reading, creating, and updating users, using the new `UserModel` and `UserCollection` models.

2024-11-18 16:11 UTC, mihaelaaleks requested changes
I've left quite a bit of comments, overall I think it's a very strong start. Solid job!

2024-11-18 16:11 UTC, mihaelaaleks commented on api/main.py
>  app = FastAPI()
Perhaps detail but good to add API metadata: 
```
app = FastAPI(
    title="Sanquin API",
    description="Etc",
    version="1.0.0"
)
```

2024-11-18 16:11 UTC, mihaelaaleks commented on api/routers/users.py
> +    users = await user_collection.find().to_list(1000)
Hardcoded limit here is a bit iffy but given the project scope it's okay.

2024-11-18 16:11 UTC, mihaelaaleks commented on api/routers/users.py
Missing error handling on the database operations.

2024-11-18 16:11 UTC, mihaelaaleks commented on api/routers/users.py
Consider a more consistent response format pattern, this is also in line with FastAPI standard practices: 

```
from fastapi import APIRouter, HTTPException, status
from typing import List
from pydantic import BaseModel

class ResponseModel(BaseModel):
    status: str
    data: dict | List | None = None
    message: str

@router.get("/", response_model=ResponseModel)
async def read_users(skip: int = 0, limit: int = 20):
    try:
        users = await user_collection.find().skip(skip).limit(limit).to_list(limit)
        return ResponseModel(
            status="success",
            data={"users": users},
            message="Users retrieved successfully"
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )
```

2024-11-18 16:11 UTC, mihaelaaleks commented on api/tests/test_main.py
Nice head start with tests!

2024-11-18 16:11 UTC, mihaelaaleks commented on api/models/user/user.py
Nice that you're thinking ahead and separating the models and API calls. 

- I would consider adding `@sensitive_fields` decorator for password. 
- Add field for password confirmation. 
- Curious why you'd leave the ID as `optional`?

2024-11-19 11:03 UTC, NinaBianca commented on api/models/user/user.py
ID is optional because it doesn't exist on first use. Gets added after User is added the DB. (Just for my information)

2024-11-19 11:38 UTC, NinaBianca commented on api/models/user/user.py
TODO: Check with frontend if they do password confirmation

2024-11-19 15:25 UTC, NinaBianca commented
CI Pipeline finally working too 💯

2024-11-20 09:43 UTC, mihaelaaleks commented on api/models/user/user.py
Awesome job! Consider following convention further by using `args` or `kwargs` instead of data. Here's [more info](https://www.geeksforgeeks.org/args-kwargs-python/) on this.

2024-11-20 09:46 UTC, mihaelaaleks commented on api/requirements.txt
Consider keeping the `requirements.txt` and `.gitignore` in the root directory of the project.

2024-11-20 09:52 UTC, mihaelaaleks commented on api/dependencies.py
Consider a way to give developers a clear idea of what your project dependencies/packages are at a glance. If I look at the `requirements.txt` then back to `dependencies.py` it's not clear to me what packages I would need. 

Dependency/package management is key in python projects. If you have time, consider replacing requirements with either Poetry or PyProject Toml.

2024-11-20 09:53 UTC, mihaelaaleks approved these changes
Strong progress, keep it up! Please see my comments on further structural and organizational improvements.

2024-11-25 11:00 UTC, NinaBianca commented
Comments added as issues for future changes!

2024-11-25 11:00 UTC, merged